export enum DormitryActionsTypes {
  GET_USER_DORMITRIES = "GET_USER_DORMITRIES",
  SET_USER_DORMITRIES = "SET_USER_DORMITRIES",
  ADD_USER_DORMITRY = "ADD_USER_DORMITRY",
  SET_ADDED_USER_DORMITRY = "SET_ADDED_USER_DORMITRY",
  LOGOUT = "LOGOUT",
}
